/*
package com.advantmods.industriallevel.common.world.oregen;

import com.advantmods.industriallevel.common.IndustrialLevel;
import com.advantmods.industriallevel.common.setup.Registration;
import com.advantmods.industriallevel.common.world.oregen.feature.FeatureConfig;
import net.minecraft.core.Registry;
import net.minecraft.data.BuiltinRegistries;
import net.minecraft.data.worldgen.features.OreFeatures;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.level.levelgen.feature.ConfiguredFeature;
import net.minecraft.world.level.levelgen.feature.Feature;
import net.minecraft.world.level.levelgen.feature.configurations.OreConfiguration;

public class OreConfigured {
    public static ConfiguredFeature<?,?> TITANIUM_ORE;
    public static ConfiguredFeature<?,?> DEEPSLATE_TITANIUM_ORE;
    public static ConfiguredFeature<?,?> NETHER_TITANIUM_ORE;
    public static ConfiguredFeature<?,?> END_TITANIUM_ORE;
    public static ConfiguredFeature<?,?> CHLOROPHYTE_ORE;
    public static ConfiguredFeature<?,?> DEEPSLATE_CHLOROPHYTE_ORE;
    public static ConfiguredFeature<?,?> NETHER_CHLOROPHYTE_ORE;
    public static ConfiguredFeature<?,?> END_CHLOROPHYTE_ORE;
    public static ConfiguredFeature<?,?> BRONZE_ORE;
    public static ConfiguredFeature<?,?> DEEPSLATE_BRONZE_ORE;
    public static ConfiguredFeature<?,?> NETHER_BRONZE_ORE;
    public static ConfiguredFeature<?,?> END_BRONZE_ORE;
    public static ConfiguredFeature<?,?> LEAD_ORE;
    public static ConfiguredFeature<?,?> DEEPSLATE_LEAD_ORE;
    public static ConfiguredFeature<?,?> NETHER_LEAD_ORE;
    public static ConfiguredFeature<?,?> END_LEAD_ORE;
    public static ConfiguredFeature<?,?> NICKEL_ORE;
    public static ConfiguredFeature<?,?> DEEPSLATE_NICKEL_ORE;
    public static ConfiguredFeature<?,?> NETHER_NICKEL_ORE;
    public static ConfiguredFeature<?,?> END_NICKEL_ORE;
    public static ConfiguredFeature<?,?> OSMIUM_ORE;
    public static ConfiguredFeature<?,?> DEEPSLATE_OSMIUM_ORE;
    public static ConfiguredFeature<?,?> NETHER_OSMIUM_ORE;
    public static ConfiguredFeature<?,?> END_OSMIUM_ORE;
    public static ConfiguredFeature<?,?> PLATINUM_ORE;
    public static ConfiguredFeature<?,?> DEEPSLATE_PLATINUM_ORE;
    public static ConfiguredFeature<?,?> NETHER_PLATINUM_ORE;
    public static ConfiguredFeature<?,?> END_PLATINUM_ORE;
    public static ConfiguredFeature<?,?> SILVER_ORE;
    public static ConfiguredFeature<?,?> DEEPSLATE_SILVER_ORE;
    public static ConfiguredFeature<?,?> NETHER_SILVER_ORE;
    public static ConfiguredFeature<?,?> END_SILVER_ORE;
    public static ConfiguredFeature<?,?> TIN_ORE;
    public static ConfiguredFeature<?,?> DEEPSLATE_TIN_ORE;
    public static ConfiguredFeature<?,?> NETHER_TIN_ORE;
    public static ConfiguredFeature<?,?> END_TIN_ORE;
    public static ConfiguredFeature<?,?> URANIUM_ORE;
    public static ConfiguredFeature<?,?> DEEPSLATE_URANIUM_ORE;
    public static ConfiguredFeature<?,?> NETHER_URANIUM_ORE;
    public static ConfiguredFeature<?,?> END_URANIUM_ORE;
    public static ConfiguredFeature<?,?> ZINC_ORE;
    public static ConfiguredFeature<?,?> DEEPSLATE_ZINC_ORE;
    public static ConfiguredFeature<?,?> NETHER_ZINC_ORE;
    public static ConfiguredFeature<?,?> END_ZINC_ORE;

    public static void register() {
        TITANIUM_ORE = Feature.ORE.configured(new OreConfiguration(OreFeatures.STONE_ORE_REPLACEABLES, Registration.TITANIUM_ORE.get().defaultBlockState(), 6));
        DEEPSLATE_TITANIUM_ORE = Feature.ORE.configured(new OreConfiguration(OreFeatures.DEEPSLATE_ORE_REPLACEABLES, Registration.DEEPSLATE_TITANIUM_ORE.get().defaultBlockState(), 6));
        NETHER_TITANIUM_ORE = Feature.ORE.configured(new OreConfiguration(OreFeatures.NETHER_ORE_REPLACEABLES, Registration.NETHER_TITANIUM_ORE.get().defaultBlockState(), 6));
        END_TITANIUM_ORE = Feature.ORE.configured(new OreConfiguration(FeatureConfig.Fill.END_STONE, Registration.END_TITANIUM_ORE.get().defaultBlockState(), 6));
        CHLOROPHYTE_ORE = Feature.ORE.configuredCodec(new OreConfiguration(OreFeatures.STONE_ORE_REPLACEABLES, Registration.CHLOROPHYTE_ORE.get().defaultBlockState(), 6));
        DEEPSLATE_CHLOROPHYTE_ORE = Feature.ORE.configured(new OreConfiguration(OreFeatures.DEEPSLATE_ORE_REPLACEABLES, Registration.DEEPSLATE_CHLOROPHYTE_ORE.get().defaultBlockState(), 6));
        NETHER_CHLOROPHYTE_ORE = Feature.ORE.configured(new OreConfiguration(OreFeatures.NETHER_ORE_REPLACEABLES, Registration.NETHER_CHLOROPHYTE_ORE.get().defaultBlockState(), 6));
        END_CHLOROPHYTE_ORE = Feature.ORE.configured(new OreConfiguration(FeatureConfig.Fill.END_STONE, Registration.END_CHLOROPHYTE_ORE.get().defaultBlockState(), 6));
        NICKEL_ORE = Feature.ORE.configured(new OreConfiguration(OreFeatures.STONE_ORE_REPLACEABLES, Registration.NICKEL_ORE.get().defaultBlockState(), 6));
        DEEPSLATE_NICKEL_ORE = Feature.ORE.configured(new OreConfiguration(OreFeatures.DEEPSLATE_ORE_REPLACEABLES, Registration.NETHER_NICKEL_ORE.get().defaultBlockState(), 6));
        NETHER_NICKEL_ORE = Feature.ORE.configured(new OreConfiguration(OreFeatures.NETHER_ORE_REPLACEABLES, Registration.NETHER_NICKEL_ORE.get().defaultBlockState(), 6));
        END_NICKEL_ORE = Feature.ORE.configured(new OreConfiguration(FeatureConfig.Fill.END_STONE, Registration.END_NICKEL_ORE.get().defaultBlockState(), 6));
        BRONZE_ORE = Feature.ORE.configured(new OreConfiguration(OreFeatures.STONE_ORE_REPLACEABLES, Registration.BRONZE_ORE.get().defaultBlockState(), 6));
        DEEPSLATE_BRONZE_ORE = Feature.ORE.configured(new OreConfiguration(OreFeatures.DEEPSLATE_ORE_REPLACEABLES, Registration.DEEPSLATE_BRONZE_ORE.get().defaultBlockState(), 6));
        NETHER_BRONZE_ORE = Feature.ORE.configured(new OreConfiguration(OreFeatures.NETHER_ORE_REPLACEABLES, Registration.NETHER_BRONZE_ORE.get().defaultBlockState(), 6));
        END_BRONZE_ORE = Feature.ORE.configured(new OreConfiguration(FeatureConfig.Fill.END_STONE, Registration.END_BRONZE_ORE.get().defaultBlockState(), 6));
        OSMIUM_ORE = Feature.ORE.configured(new OreConfiguration(OreFeatures.STONE_ORE_REPLACEABLES, Registration.OSMIUM_ORE.get().defaultBlockState(), 6));
        DEEPSLATE_OSMIUM_ORE = Feature.ORE.configured(new OreConfiguration(OreFeatures.DEEPSLATE_ORE_REPLACEABLES, Registration.DEEPSLATE_OSMIUM_ORE.get().defaultBlockState(), 6));
        NETHER_OSMIUM_ORE = Feature.ORE.configured(new OreConfiguration(OreFeatures.NETHER_ORE_REPLACEABLES, Registration.NETHER_OSMIUM_ORE.get().defaultBlockState(), 6));
        END_OSMIUM_ORE = Feature.ORE.configured(new OreConfiguration(FeatureConfig.Fill.END_STONE, Registration.END_OSMIUM_ORE.get().defaultBlockState(), 6));
        PLATINUM_ORE = Feature.ORE.configured(new OreConfiguration(OreFeatures.STONE_ORE_REPLACEABLES, Registration.PLATINUM_ORE.get().defaultBlockState(), 6));
        DEEPSLATE_PLATINUM_ORE = Feature.ORE.configured(new OreConfiguration(OreFeatures.DEEPSLATE_ORE_REPLACEABLES, Registration.DEEPSLATE_PLATINUM_ORE.get().defaultBlockState(), 6));
        NETHER_PLATINUM_ORE = Feature.ORE.configured(new OreConfiguration(OreFeatures.NETHER_ORE_REPLACEABLES, Registration.NETHER_PLATINUM_ORE.get().defaultBlockState(), 6));
        END_PLATINUM_ORE = Feature.ORE.configured(new OreConfiguration(FeatureConfig.Fill.END_STONE, Registration.END_PLATINUM_ORE.get().defaultBlockState(), 6));
        URANIUM_ORE = Feature.ORE.configured(new OreConfiguration(OreFeatures.STONE_ORE_REPLACEABLES, Registration.URANIUM_ORE.get().defaultBlockState(), 6));
        DEEPSLATE_URANIUM_ORE = Feature.ORE.configured(new OreConfiguration(OreFeatures.DEEPSLATE_ORE_REPLACEABLES, Registration.DEEPSLATE_URANIUM_ORE.get().defaultBlockState(), 6));
        NETHER_URANIUM_ORE = Feature.ORE.configured(new OreConfiguration(OreFeatures.NETHER_ORE_REPLACEABLES, Registration.NETHER_URANIUM_ORE.get().defaultBlockState(), 6));
        END_URANIUM_ORE = Feature.ORE.configured(new OreConfiguration(FeatureConfig.Fill.END_STONE, Registration.END_URANIUM_ORE.get().defaultBlockState(), 6));
        LEAD_ORE = Feature.ORE.configured(new OreConfiguration(OreFeatures.STONE_ORE_REPLACEABLES, Registration.LEAD_ORE.get().defaultBlockState(), 6));
        DEEPSLATE_LEAD_ORE = Feature.ORE.configured(new OreConfiguration(OreFeatures.DEEPSLATE_ORE_REPLACEABLES, Registration.DEEPSLATE_LEAD_ORE.get().defaultBlockState(), 6));
        NETHER_LEAD_ORE = Feature.ORE.configured(new OreConfiguration(OreFeatures.NETHER_ORE_REPLACEABLES, Registration.NETHER_LEAD_ORE.get().defaultBlockState(), 6));
        END_LEAD_ORE = Feature.ORE.configured(new OreConfiguration(FeatureConfig.Fill.END_STONE, Registration.END_LEAD_ORE.get().defaultBlockState(), 6));
        ZINC_ORE = Feature.ORE.configured(new OreConfiguration(OreFeatures.STONE_ORE_REPLACEABLES, Registration.ZINC_ORE.get().defaultBlockState(), 6));
        DEEPSLATE_ZINC_ORE = Feature.ORE.configured(new OreConfiguration(OreFeatures.DEEPSLATE_ORE_REPLACEABLES, Registration.DEEPSLATE_ZINC_ORE.get().defaultBlockState(), 6));
        NETHER_ZINC_ORE = Feature.ORE.configured(new OreConfiguration(OreFeatures.NETHER_ORE_REPLACEABLES, Registration.NETHER_ZINC_ORE.get().defaultBlockState(), 6));
        END_ZINC_ORE = Feature.ORE.configured(new OreConfiguration(FeatureConfig.Fill.END_STONE, Registration.END_ZINC_ORE.get().defaultBlockState(), 6));
        TIN_ORE = Feature.ORE.configured(new OreConfiguration(OreFeatures.STONE_ORE_REPLACEABLES, Registration.TIN_ORE.get().defaultBlockState(), 6));
        DEEPSLATE_TIN_ORE = Feature.ORE.configured(new OreConfiguration(OreFeatures.DEEPSLATE_ORE_REPLACEABLES, Registration.DEEPSLATE_TIN_ORE.get().defaultBlockState(), 6));
        NETHER_TIN_ORE = Feature.ORE.configured(new OreConfiguration(OreFeatures.NETHER_ORE_REPLACEABLES, Registration.NETHER_TIN_ORE.get().defaultBlockState(), 6));
        END_TIN_ORE = Feature.ORE.configured(new OreConfiguration(FeatureConfig.Fill.END_STONE, Registration.END_TIN_ORE.get().defaultBlockState(), 6));
        SILVER_ORE = Feature.ORE.configured(new OreConfiguration(OreFeatures.STONE_ORE_REPLACEABLES, Registration.SILVER_ORE.get().defaultBlockState(), 6));
        DEEPSLATE_SILVER_ORE = Feature.ORE.configured(new OreConfiguration(OreFeatures.DEEPSLATE_ORE_REPLACEABLES, Registration.DEEPSLATE_SILVER_ORE.get().defaultBlockState(), 6));
        NETHER_SILVER_ORE = Feature.ORE.configured(new OreConfiguration(OreFeatures.NETHER_ORE_REPLACEABLES, Registration.NETHER_SILVER_ORE.get().defaultBlockState(), 6));
        END_SILVER_ORE = Feature.ORE.configured(new OreConfiguration(FeatureConfig.Fill.END_STONE, Registration.END_SILVER_ORE.get().defaultBlockState(), 6));

        // Register the configured features
        Registry.register(BuiltinRegistries.CONFIGURED_FEATURE, new ResourceLocation(IndustrialLevel.ModId, "titanium_ore"), TITANIUM_ORE);
        Registry.register(BuiltinRegistries.CONFIGURED_FEATURE, new ResourceLocation(IndustrialLevel.ModId, "deepslate_titanium_ore"), DEEPSLATE_TITANIUM_ORE);
        Registry.register(BuiltinRegistries.CONFIGURED_FEATURE, new ResourceLocation(IndustrialLevel.ModId, "nether_titanium_ore"), NETHER_TITANIUM_ORE);
        Registry.register(BuiltinRegistries.CONFIGURED_FEATURE, new ResourceLocation(IndustrialLevel.ModId, "end_titanium_ore"), END_TITANIUM_ORE);
        Registry.register(BuiltinRegistries.CONFIGURED_FEATURE, new ResourceLocation(IndustrialLevel.ModId, "chlorophyte_ore"), CHLOROPHYTE_ORE);
        Registry.register(BuiltinRegistries.CONFIGURED_FEATURE, new ResourceLocation(IndustrialLevel.ModId, "deepslate_chlorophyte_ore"), DEEPSLATE_CHLOROPHYTE_ORE);
        Registry.register(BuiltinRegistries.CONFIGURED_FEATURE, new ResourceLocation(IndustrialLevel.ModId, "nether_chlorophyte_ore"), NETHER_CHLOROPHYTE_ORE);
        Registry.register(BuiltinRegistries.CONFIGURED_FEATURE, new ResourceLocation(IndustrialLevel.ModId, "end_chlorophyte_ore"), END_CHLOROPHYTE_ORE);
        Registry.register(BuiltinRegistries.CONFIGURED_FEATURE, new ResourceLocation(IndustrialLevel.ModId, "bronze_ore"), BRONZE_ORE);
        Registry.register(BuiltinRegistries.CONFIGURED_FEATURE, new ResourceLocation(IndustrialLevel.ModId, "deepslate_bronze_ore"), DEEPSLATE_BRONZE_ORE);
        Registry.register(BuiltinRegistries.CONFIGURED_FEATURE, new ResourceLocation(IndustrialLevel.ModId, "nether_bronze_ore"), NETHER_BRONZE_ORE);
        Registry.register(BuiltinRegistries.CONFIGURED_FEATURE, new ResourceLocation(IndustrialLevel.ModId, "end_bronze_ore"), END_BRONZE_ORE);
        Registry.register(BuiltinRegistries.CONFIGURED_FEATURE, new ResourceLocation(IndustrialLevel.ModId, "lead_ore"), LEAD_ORE);
        Registry.register(BuiltinRegistries.CONFIGURED_FEATURE, new ResourceLocation(IndustrialLevel.ModId, "deepslate_lead_ore"), DEEPSLATE_LEAD_ORE);
        Registry.register(BuiltinRegistries.CONFIGURED_FEATURE, new ResourceLocation(IndustrialLevel.ModId, "nether_lead_ore"), NETHER_LEAD_ORE);
        Registry.register(BuiltinRegistries.CONFIGURED_FEATURE, new ResourceLocation(IndustrialLevel.ModId, "end_lead_ore"), END_LEAD_ORE);
        Registry.register(BuiltinRegistries.CONFIGURED_FEATURE, new ResourceLocation(IndustrialLevel.ModId, "nickel_ore"), NICKEL_ORE);
        Registry.register(BuiltinRegistries.CONFIGURED_FEATURE, new ResourceLocation(IndustrialLevel.ModId, "deepslate_nickel_ore"), DEEPSLATE_NICKEL_ORE);
        Registry.register(BuiltinRegistries.CONFIGURED_FEATURE, new ResourceLocation(IndustrialLevel.ModId, "nether_nickel_ore"), NETHER_NICKEL_ORE);
        Registry.register(BuiltinRegistries.CONFIGURED_FEATURE, new ResourceLocation(IndustrialLevel.ModId, "end_nickel_ore"), END_NICKEL_ORE);
        Registry.register(BuiltinRegistries.CONFIGURED_FEATURE, new ResourceLocation(IndustrialLevel.ModId, "osmium_ore"), OSMIUM_ORE);
        Registry.register(BuiltinRegistries.CONFIGURED_FEATURE, new ResourceLocation(IndustrialLevel.ModId, "deepslate_osmium_ore"), DEEPSLATE_OSMIUM_ORE);
        Registry.register(BuiltinRegistries.CONFIGURED_FEATURE, new ResourceLocation(IndustrialLevel.ModId, "nether_osmium_ore"), NETHER_OSMIUM_ORE);
        Registry.register(BuiltinRegistries.CONFIGURED_FEATURE, new ResourceLocation(IndustrialLevel.ModId, "end_osmium_ore"), END_OSMIUM_ORE);
        Registry.register(BuiltinRegistries.CONFIGURED_FEATURE, new ResourceLocation(IndustrialLevel.ModId, "platinum_ore"), PLATINUM_ORE);
        Registry.register(BuiltinRegistries.CONFIGURED_FEATURE, new ResourceLocation(IndustrialLevel.ModId, "deepslate_platinum_ore"), DEEPSLATE_PLATINUM_ORE);
        Registry.register(BuiltinRegistries.CONFIGURED_FEATURE, new ResourceLocation(IndustrialLevel.ModId, "nether_platinum_ore"), NETHER_PLATINUM_ORE);
        Registry.register(BuiltinRegistries.CONFIGURED_FEATURE, new ResourceLocation(IndustrialLevel.ModId, "end_platinum_ore"), END_PLATINUM_ORE);
        Registry.register(BuiltinRegistries.CONFIGURED_FEATURE, new ResourceLocation(IndustrialLevel.ModId, "silver_ore"), SILVER_ORE);
        Registry.register(BuiltinRegistries.CONFIGURED_FEATURE, new ResourceLocation(IndustrialLevel.ModId, "deepslate_silver_ore"), DEEPSLATE_SILVER_ORE);
        Registry.register(BuiltinRegistries.CONFIGURED_FEATURE, new ResourceLocation(IndustrialLevel.ModId, "nether_silver_ore"), NETHER_SILVER_ORE);
        Registry.register(BuiltinRegistries.CONFIGURED_FEATURE, new ResourceLocation(IndustrialLevel.ModId, "end_silver_ore"), END_SILVER_ORE);
        Registry.register(BuiltinRegistries.CONFIGURED_FEATURE, new ResourceLocation(IndustrialLevel.ModId, "tin_ore"), TIN_ORE);
        Registry.register(BuiltinRegistries.CONFIGURED_FEATURE, new ResourceLocation(IndustrialLevel.ModId, "deepslate_tin_ore"), DEEPSLATE_TIN_ORE);
        Registry.register(BuiltinRegistries.CONFIGURED_FEATURE, new ResourceLocation(IndustrialLevel.ModId, "nether_tin_ore"), NETHER_TIN_ORE);
        Registry.register(BuiltinRegistries.CONFIGURED_FEATURE, new ResourceLocation(IndustrialLevel.ModId, "end_tin_ore"), END_TIN_ORE);
        Registry.register(BuiltinRegistries.CONFIGURED_FEATURE, new ResourceLocation(IndustrialLevel.ModId, "uranium_ore"), URANIUM_ORE);
        Registry.register(BuiltinRegistries.CONFIGURED_FEATURE, new ResourceLocation(IndustrialLevel.ModId, "deepslate_uranium_ore"), DEEPSLATE_URANIUM_ORE);
        Registry.register(BuiltinRegistries.CONFIGURED_FEATURE, new ResourceLocation(IndustrialLevel.ModId, "nether_uranium_ore"), NETHER_URANIUM_ORE);
        Registry.register(BuiltinRegistries.CONFIGURED_FEATURE, new ResourceLocation(IndustrialLevel.ModId, "end_uranium_ore"), END_URANIUM_ORE);
        Registry.register(BuiltinRegistries.CONFIGURED_FEATURE, new ResourceLocation(IndustrialLevel.ModId, "zinc_ore"), ZINC_ORE);
        Registry.register(BuiltinRegistries.CONFIGURED_FEATURE, new ResourceLocation(IndustrialLevel.ModId, "deepslate_zinc_ore"), DEEPSLATE_ZINC_ORE);
        Registry.register(BuiltinRegistries.CONFIGURED_FEATURE, new ResourceLocation(IndustrialLevel.ModId, "nether_zinc_ore"), NETHER_ZINC_ORE);
        Registry.register(BuiltinRegistries.CONFIGURED_FEATURE, new ResourceLocation(IndustrialLevel.ModId, "end_zinc_ore"), END_ZINC_ORE);
    }
}
*/
